
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzi7GzJPzq6n6QidwLKb19NdsMRnLailA',
    appId: '1:876583201990:web:d70115f4b05c74109f3bc7',
    messagingSenderId: '876583201990',
    projectId: 'fir-flutter-codelab-50fe3',
    authDomain: 'fir-flutter-codelab-50fe3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-50fe3.appspot.com',
    measurementId: 'G-Q0LH5KKPLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeBJD3OohyGa2TGnOnOEwjrv4XTXE7f-U',
    appId: '1:876583201990:android:fb7b58992c9d1f8a9f3bc7',
    messagingSenderId: '876583201990',
    projectId: 'fir-flutter-codelab-50fe3',
    storageBucket: 'fir-flutter-codelab-50fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwhbbM7QVKAAWxu9I_6Bj8lCe0oFDt_WA',
    appId: '1:876583201990:ios:173b80a360f08e799f3bc7',
    messagingSenderId: '876583201990',
    projectId: 'fir-flutter-codelab-50fe3',
    storageBucket: 'fir-flutter-codelab-50fe3.appspot.com',
    iosClientId:
        '876583201990-a7amf702v45esgnkb45vgckorun5e4fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwhbbM7QVKAAWxu9I_6Bj8lCe0oFDt_WA',
    appId: '1:876583201990:ios:173b80a360f08e799f3bc7',
    messagingSenderId: '876583201990',
    projectId: 'fir-flutter-codelab-50fe3',
    storageBucket: 'fir-flutter-codelab-50fe3.appspot.com',
    iosClientId:
        '876583201990-a7amf702v45esgnkb45vgckorun5e4fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
